definitions:
  domain.OfferCompany:
    properties:
      client_id:
        type: integer
      country:
        type: string
      flag:
        type: integer
      image:
        type: string
      image_height:
        type: integer
      image_width:
        type: integer
      offer_home:
        type: integer
      offer_id:
        type: integer
      page_count:
        type: integer
      position:
        type: integer
      show_from:
        type: string
      store_url:
        type: string
      store_url_title:
        type: string
      text_locale:
        type: string
      valid_from:
        type: string
      valid_to:
        type: string
      validity_text_locale:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/offer-company/{country_name}:
    get:
      description: Get all companies
      operationId: FindAll
      parameters:
      - description: Data Format
        in: header
        name: data_format
        required: true
        type: string
      - description: Country Name
        in: path
        name: country_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.OfferCompany'
            type: array
      security:
      - ApiKeyAuth: []
      summary: Get all offer companies
      tags:
      - Offer
swagger: "2.0"
