// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/sreenathsvrm/voix-me/pkg/api"
	"github.com/sreenathsvrm/voix-me/pkg/api/handler"
	"github.com/sreenathsvrm/voix-me/pkg/config"
	"github.com/sreenathsvrm/voix-me/pkg/db"
	"github.com/sreenathsvrm/voix-me/pkg/repository"
	"github.com/sreenathsvrm/voix-me/pkg/service"
	"github.com/sreenathsvrm/voix-me/pkg/usecase"
)

// Injectors from wire.go:

func InitializeAPI(cfg config.Config) (*http.ServerHTTP, error) {
	gormDB, err := db.ConnectDatabase(cfg)
	if err != nil {
		return nil, err
	}
	offerRepository := repository.NewOfferCompanyRepository(gormDB)
	inMemoryStorage := service.NewInMemoryStorage()
	offerUseCase := usecase.NewOfferCompanyUseCase(offerRepository, inMemoryStorage)
	offerCompanyHandler := handler.NewOfferCompanyHandler(offerUseCase)
	serverHTTP := http.NewServerHTTP(cfg, offerCompanyHandler)
	return serverHTTP, nil
}
